server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include: secrets
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${port}/${db-name}
    username: ${db-username}
    password: ${db-password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        properties:
#          hibernate:
#            format_sql: true
#            default_batch_fetch_size: 100 # 최적화 옵션
#            # 100 ~ 1000 이 적당. 크게 잡을 수록 DB에 가해지는 순간 부하가 크며, 작게 할 수록 전송되는 쿼리의 수와 대기 시간이 증가한다.
#            # 100 정도로 두고 조금씩 늘리며 테스트해 보는 것이 좋다.
#  logging.level:
#    org.hibernate.SQL: debug